version: 2
updates:
  # Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
    ignore:
      - dependency-name: "libservo"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "mikopet"
    commit-message:
      prefix: ":arrow_up: [dependabot] "
  # GHA
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    reviewers:
      - "mikopet"
    commit-message:
      prefix: ":arrow_up: [dependabot] "

